export const EMAIL_ONCHANGE = "EMAIL_ONCHANGE"
export const PASSWORD_ONCHANGE = "PASSWORD_ONCHANGE"
export const LOGOUT = "LOGOUT"

export const SLIDE_GET_REQUEST = "SLIDE_GET_REQUEST"
export const SLIDE_GET_SUCCESS = "SLIDE_GET_SUCCESS"
export const SLIDE_GET_FAILURE = "SLIDE_GET_FAILURE"

export const SLIDE_CHANGE = "SLIDE_CHANGE"
export const SLIDE_LAST = "SLIDE_LAST"
export const SLIDE_FIRST = "SLIDE_FIRST"

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const SIGNUP_REQUEST = "SIGNUP_REQUEST"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAILURE = "SIGNUP_FAILURE"

export const GET_CART_PRODUCT_REQUEST = "GET_CART_PRODUCT_REQUEST"
export const GET_CART_PRODUCT_SUCCESS = "GET_CART_PRODUCT_SUCCESS"
export const GET_CART_PRODUCT_FAILURE = "GET_CART_PRODUCT_FAILURE"

export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"

export const PAGE_PREV = "PAGE_PREV"
export const PAGE_NEXT = "PAGE_NEXT"
export const LIMIT = "LIMIT"

export const GET_SINGLE_PRODUCT_REQUEST = "GET_SINGLE_PRODUCT_REQUEST"
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS"
export const GET_SINGLE_PRODUCT_FAILURE = "GET_SINGLE_PRODUCT_FAILURE"

export const GET_CHECKOUT_DETAILS_REQUEST = "GET_CHECKOUT_DETAILS_REQUEST"
export const GET_CHECKOUT_DETAILS_SUCCESS = "GET_CHECKOUT_DETAILS_SUCCESS"
export const GET_CHECKOUT_DETAILS_FAILURE = "GET_CHECKOUT_DETAILS_FAILURE"

export const FORM_EMAIL_ONCHANGE = "FORM_EMAIL_ONCHANGE"
export const FIRSTNAME_ONCHANGE = "FIRSTNAME_ONCHANGE"
export const LASTNAME_ONCHANGE = "LASTNAME_ONCHANGE"
export const MOBILE_ONCHANGE = "MOBILE_ONCHANGE"
export const ADDRESS_ONCHANGE = "ADDRESS_ONCHANGE"
export const CITY_ONCHANGE = "CITY_ONCHANGE"
export const COUNTRY_ONCHANGE = "COUNTRY_ONCHANGE"

export const PALACE_ORDER_REQUEST = "PALACE_ORDER_REQUEST"
export const PALACE_ORDER_SUCCESS = "PALACE_ORDER_SUCCESS"
export const PALACE_ORDER_FAILURE = "PALACE_ORDER_FAILURE"